apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
  labels:
    app: your-app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-container
        image: your-docker-image:latest  # Docker image to use
        ports:
        - containerPort: 8080  # Port on which your application listens
