apiVersion: v1
kind: Service
metadata:
  name: your-service
spec:
  selector:
    app: your-app  # Label selector to match the pods belonging to your application
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on which your application is listening in the pods
  type: LoadBalancer  # Expose the service outside the cluster using a cloud provider's load balancer
