apiVersion: v1
kind: Service
metadata:
  name: optit-lab-python1-service
  namespace: optit-lab-python1
spec:
  selector:
    app: optit-lab-python1-service
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8585
  